const {
  ATHENA_DATABASE,
  ATHENA_BUCKET,
  ATHENA_BUCKET_QUERY_RESULTS,
  ATHENA_BUCKET_QUERY_RESULTS_FULL_PATH,
  ATHENA_GLUE_CRAWLER,
  ATHENA_PAGE_LIMIT,
  ATHENA_MAX_PAGE_LIMIT,
} = process.env;

module.exports = {
  ATHENA_DATABASE,
  ATHENA_BUCKET,
  ATHENA_BUCKET_QUERY_RESULTS,
  ATHENA_BUCKET_QUERY_RESULTS_FULL_PATH,
  ATHENA_GLUE_CRAWLER,
  ATHENA_PAGE_LIMIT,
  ATHENA_MAX_PAGE_LIMIT,
}